benches: deku: Annotate CountFromCtxWrapper with #[expected(dead_code)]
The struct was introduced in 59fc7603e2eb ("Add count Vec<u8>
Specializations (#481)") but yields:

     error: struct `CountFromCtxWrapper` is never constructed
        --> benches/deku.rs:135:16
         |
     135 |     pub struct CountFromCtxWrapper {
         |                ^^^^^^^^^^^^^^^^^^^
         |
         = note: `-D dead-code` implied by `-D warnings`
         = help: to override `-D warnings` add `#[allow(dead_code)]`

Mark it as expected for now.

Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>