tests: test_own_impl: Drop unused ReadSeek
Eliminate:

    error: trait `ReadSeek` is never used
     --> tests/test_own_impl.rs:5:15
      |
    5 |     pub trait ReadSeek: Read + Seek {}
      |               ^^^^^^^^
      |
      = note: `-D dead-code` implied by `-D warnings`
      = help: to override `-D warnings` add `#[allow(dead_code)]`

Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>