tests: test_common: Ignore dead code warning for from_be_bytes()
Eliminate:

    error: associated function `from_be_bytes` is never used
     --> tests/test_common/mod.rs:5:8
      |
    3 | pub trait FromBeBytes: Sized {
      |           ----------- associated function in this trait
    4 |     type Bytes;
    5 |     fn from_be_bytes(_: Self::Bytes) -> Self;
      |        ^^^^^^^^^^^^^
      |
      = note: `-D dead-code` implied by `-D warnings`
      = help: to override `-D warnings` add `#[allow(dead_code)]`

It is used in some test suites, just not all.

Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>