tests: test_struct: Tidy unused variable warnings
Eliminate:

     error: unused variable: `y`
        --> tests/test_struct.rs:248:10
         |
     248 |     let (y, x) = ListOfThings::from_bytes((&bytes, 0)).unwrap();
         |          ^ help: if this is intentional, prefix it with an underscore: `_y`
         |
         = note: `-D unused-variables` implied by `-D warnings`
         = help: to override `-D warnings` add `#[allow(unused_variables)]`

     error: unused variable: `y`
        --> tests/test_struct.rs:264:10
         |
     264 |     let (y, x) = ListOfThings::from_bytes((&bytes, 0)).unwrap();
         |          ^ help: if this is intentional, prefix it with an underscore: `_y`

Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>