cstring: Switch to byte strings
Eliminate warnings such as:

    error: can be more succinctly written as a byte str
      --> tests/test_cstring.rs:12:17
       |
    12 |     let bytes = &[b't', b'e', b's', b't', b'\0'];
       |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `b"test\0"`
       |
       = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#byte_char_slices
       = note: `-D clippy::byte-char-slices` implied by `-D warnings`
       = help: to override `-D warnings` add `#[allow(clippy::byte_char_slices)]`

Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>