tests: test_own_impl: Annotate Data with #[expect(dead_code)]
The expectation failed, and further, dead_code triggered on the enum
type itself:

    error: enum `Data` is never used
     --> tests/test_own_impl.rs:5:14
      |
    5 |     pub enum Data {
      |              ^^^^
      |
      = note: `-D dead-code` implied by `-D warnings`
      = help: to override `-D warnings` add `#[allow(dead_code)]`

    error: this lint expectation is unfulfilled
     --> tests/test_own_impl.rs:8:18
      |
    8 |         #[expect(dead_code)]
      |                  ^^^^^^^^^
      |
      = note: `-D unfulfilled-lint-expectations` implied by `-D warnings`
      = help: to override `-D warnings` add `#[allow(unfulfilled_lint_expectations)]`

Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>