benches: deku: Switch to std::hint::black_box()
Eliminate:

    error: use of deprecated function `criterion::black_box`: use `std::hint::black_box()` instead
     --> benches/deku.rs:3:17
      |
    3 | use criterion::{black_box, criterion_group, criterion_main, BatchSize, Criterion};
      |                 ^^^^^^^^^
      |
      = note: `-D deprecated` implied by `-D warnings`
      = help: to override `-D warnings` add `#[allow(deprecated)]`

Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>