tests: test_alloc: Annotate NestedEnum2 with #[expect(dead_code)]
The type is mentioned in commentary on a separate struct, so keep it
for now. Addresses:

    error: enum `NestedEnum2` is never used
      --> tests/test_alloc.rs:28:6
       |
    28 | enum NestedEnum2 {
       |      ^^^^^^^^^^^
       |
       = note: `-D dead-code` implied by `-D warnings`
       = help: to override `-D warnings` add `#[allow(dead_code)]`

Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>